var fs = require('fs')
	, hogan = require('hogan.js');

function denoteLast(collection, target)
{
	collection.forEach(function(item) {
		var itemTarget = item[target];
		if (! itemTarget || itemTarget.length == 0) return;
		itemTarget[itemTarget.length - 1].hm__last = true;
	});
}

var M = {
	version: '0.0.1',

	_templateCache: {},

	targets: {
			client: 'client'
		, server: 'server'
	},

	languages: {
			php: 'php'
		, csharp: 'csharp'
	},

	primitives: {
			char: 'char'
		, string: 'string'
		, short: 'short'
		, int: 'int'
		, long: 'long'
		, float: 'float'
		, double: 'double'
		, bool: 'bool'
	},

	_process: function(f, data) {
		if (typeof M._templateCache[f] == 'undefined') M._templateCache[f] = hogan.compile( fs.readFileSync(f).toString() );
		var template = M._templateCache[f];

		return template.render(data);
	},

	build: function(target, language, base, spec, cb) {
		if (typeof M.languages[ language ] == 'undefined') throw new Error('Invalid language specified.  Valid languages: ' + Object.keys(M.languages).join(', '));
		if (typeof M.targets[ target ] == 'undefined') throw new Error('Invalid target specified.  Valid targets: ' + Object.keys(M.targets).join(', '));
		if (!cb) cb = function(suggestedFilename, code, type, name) { console.log(code); } ;

		if (typeof base != 'string') cb = spec, spec = base, base = 'base'; // default to the base.mustache base base basebase base

		var processor = require('./processors/' + target + 's/' + language + '.js')
			, objects = spec.objects
			, code = [];

		processor.preprocess(objects);

		denoteLast(objects, 'properties');

		objects.forEach(function(object) {
			denoteLast(object.methods, 'parameters');
		});

		var templateApi = __dirname + '/templates/' + target + 's/' + language + '/api.mustache'
			, templateObject = __dirname + '/templates/' + target + 's/' + language + '/object.mustache'
			, templateEdit = __dirname + '/templates/' + target + 's/' + language + '/edit.mustache'
			, templateBase = __dirname + '/templates/' + target + 's/' + language + '/base/' + base + '.mustache';

		spec.autogenerated = [
				'!!! This file was automatically generated.  If you edit this file, your changes may be overwritten. !!!'
			, 'This file was automatically generated using helpermonkey v' + M.version + ', which'
			, 'is available at https://github.com/cmawhorter/helpermonkey'
		];

		var apiCode = M._process(templateApi, spec)
			, baseCode = M._process(templateBase, spec);

		cb(processor.fileName(spec, 'api', spec.api_name), processor.postprocess(apiCode), 'api', spec.api_name); code.push(new Buffer(apiCode));
		cb(processor.fileName(spec, 'base', 'Base'), processor.postprocess(baseCode), 'base', 'Base'); code.push(new Buffer(baseCode));

		objects.forEach(function(object) {

			// add references to api_* properties to each object
			for (var k in spec)
			{
				if (k.substr(0, 4) == 'api_')
				{
					object[k] = spec[k];
				}
			}

			var objectCode = M._process(templateObject, object);
			cb(processor.fileName(spec, 'object', object.object), processor.postprocess(objectCode), 'object', object.object); code.push(new Buffer(objectCode));

			var editCode = M._process(templateEdit, object);
			cb(processor.fileName(spec, 'edit', object.object), processor.postprocess(editCode), 'edit', object.object); code.push(new Buffer(editCode));
		});

		return processor.postprocess( Buffer.concat(code).toString() );
	}
};

module.exports = M;